export const minPasswordLength = 12;
export const maxPasswordLength = 40;
export const alpha = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
export const numbers = '0123456789';
export const symbols = '!@#$%^&*_-+=';
export const STORAGE_ENUMS = {
	LOAD_SAVED_CREDENTIALS: 'LOAD_SAVED_CREDENTIALS',
	HANDLE_LOAD_SAVED_CREDENTIALS: 'HANDLE_LOAD_SAVED_CREDENTIALS',
	SAVE_CREDENTIAL: 'SAVE_CREDENTIAL',
	HANDLE_SAVE_CREDENTIAL: 'HANDLE_SAVE_CREDENTIAL',
	DELETE_CREDENTIAL: 'DELETE_CREDENTIAL',
	HANDLE_DELETE_CREDENTIAL: 'HANDLE_DELETE_CREDENTIAL'
}